# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10

script:
  xcodebuild clean test -workspace EndpointProcedure.xcworkspace -scheme All -destination "platform=OS X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
after_success:
  bash <(curl -s https://codecov.io/bash) -J 'All'

# os: osx
# osx_image: xcode9.4
# cache: cocoapods
# podfile: Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install
# script:
# - set -o pipefail && xcodebuild test -workspace EndpointProcedure.xcworkspace -scheme All -sdk iphonesimulator11.4 -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.4' ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
